services:
  web:
    build: .
    # command:
    volumes:
      - .:/src
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/gates_test
      - JWT_KEY="supersecretgateskey"
      - MAILCHIMP_KEY="c5cff89aad73f29ba4d647fd5959b4d9-us18"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=gates

volumes:
  postgres_data:
