services:
  web:
    build: .
    # command:
    volumes:
      - .:/src
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/gates_test
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=gates

volumes:
  postgres_data:
