services:
  web:
    build: .
    # command:
    volumes:
      - .:/src
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/gates_test
      - SECRET_KEY="supersecretgateskey"
      - CLOUD_NAME="dh7dv7qie"
      - CLOUDINARY_API_KEY="391552849179997"
      - CLOUDINARY_API_SECRET="_nWsXIg9rRJLiAderKlAe5ataaw"
      - POSTMARK_API_KEY="c0496911-30dc-4fee-a2ed-a3c930d45986"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=gates

volumes:
  postgres_data:
